/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    AuditLogs: () => import('#controllers/admin/audit_logs_controller'),
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Dealers: () => import('#controllers/admin/dealers_controller'),
    Devices: () => import('#controllers/admin/devices_controller'),
    Export: () => import('#controllers/admin/export_controller'),
    SalesEntries: () => import('#controllers/admin/sales_entries_controller'),
    Towns: () => import('#controllers/admin/towns_controller'),
    Users: () => import('#controllers/admin/users_controller'),
  },
  Auth: () => import('#controllers/auth_controller'),
  dealer: {
    Export: () => import('#controllers/dealer/export_controller'),
    SalesEntries: () => import('#controllers/dealer/sales_entries_controller'),
  },
  shared: {
    Lookup: () => import('#controllers/shared/lookup_controller'),
  },
}
