/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'changes', 'createdAt', 'entity', 'entityId', 'id', 'userId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare changes: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare entity: string
  @column()
  declare entityId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
}

export class DealerSchema extends BaseModel {
  static $columns = ['createdAt', 'dealerCategory', 'id', 'location', 'ownerName', 'phoneNumber', 'shopName', 'townId', 'updatedAt', 'userId'] as const
  $columns = DealerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dealerCategory: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare location: string | null
  @column()
  declare ownerName: string | null
  @column()
  declare phoneNumber: string
  @column()
  declare shopName: string | null
  @column()
  declare townId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class DeviceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'marketingName', 'memory', 'updatedAt'] as const
  $columns = DeviceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare marketingName: string
  @column()
  declare memory: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MakeFullNameNullableOnUserSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt'] as const
  $columns = MakeFullNameNullableOnUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SalesEntrySchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'customerName', 'dealerId', 'id', 'supplierName', 'townId', 'updatedAt'] as const
  $columns = SalesEntrySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: number | null
  @column()
  declare customerName: string
  @column()
  declare dealerId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare supplierName: string | null
  @column()
  declare townId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SalesLineSchema extends BaseModel {
  static $columns = ['createdAt', 'deviceId', 'id', 'imei', 'quantity', 'salesEntryId', 'updatedAt'] as const
  $columns = SalesLineSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare deviceId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imei: string | null
  @column()
  declare quantity: number
  @column()
  declare salesEntryId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TownSchema extends BaseModel {
  static $columns = ['createdAt', 'division', 'id', 'region', 'townName', 'updatedAt'] as const
  $columns = TownSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare division: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare region: string
  @column()
  declare townName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'password', 'role', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
}
